// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUxTRVUM4XBDKE9sONT8B13-6Ia3msG94',
    appId: '1:391668425968:web:70e8bfc825d686402f0e35',
    messagingSenderId: '391668425968',
    projectId: 'to-do-list-f70a1',
    authDomain: 'to-do-list-f70a1.firebaseapp.com',
    storageBucket: 'to-do-list-f70a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2z-5dxukTbZs9ASOgnBGta2jSquuf0SY',
    appId: '1:391668425968:android:76a0eb07771ab9c72f0e35',
    messagingSenderId: '391668425968',
    projectId: 'to-do-list-f70a1',
    storageBucket: 'to-do-list-f70a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAso8vje1vjNm2utGqogf1FESoyutYbKiU',
    appId: '1:391668425968:ios:cd662a42342a2b102f0e35',
    messagingSenderId: '391668425968',
    projectId: 'to-do-list-f70a1',
    storageBucket: 'to-do-list-f70a1.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAso8vje1vjNm2utGqogf1FESoyutYbKiU',
    appId: '1:391668425968:ios:cd662a42342a2b102f0e35',
    messagingSenderId: '391668425968',
    projectId: 'to-do-list-f70a1',
    storageBucket: 'to-do-list-f70a1.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUxTRVUM4XBDKE9sONT8B13-6Ia3msG94',
    appId: '1:391668425968:web:dbc0fb352b4eab4c2f0e35',
    messagingSenderId: '391668425968',
    projectId: 'to-do-list-f70a1',
    authDomain: 'to-do-list-f70a1.firebaseapp.com',
    storageBucket: 'to-do-list-f70a1.firebasestorage.app',
  );

}